
package frame;
import javax.swing.JOptionPane;
import model.Kategori;
import table.KategoriTable;

/**
 *
 * @author Ahya Ghifari
 */
public class KategoriFormFrame extends javax.swing.JFrame {

    private final AdminFrame adminFrame;
    private final String status;
    
    /**
     * Creates new form KategoriFormFrame
     * @param adminFrame
     * @param newId
     */

    // KONSTRUKTOR UNTUK TAMBAH
    public KategoriFormFrame(AdminFrame adminFrame, String newId) {
        initComponents();
        this.adminFrame = adminFrame;
        
        tfId.setText(newId);
        
        status = "TAMBAH";
        lblTitle.setText("Tambah Kategori");
    }
    
    // KONTRUKTOR UNTUK EDIT
    public KategoriFormFrame(AdminFrame adminFrame, Kategori kategori) {
        initComponents();
        
        this.adminFrame = adminFrame;
        
        // mengisi form sesuai kategori yang dipilih
        tfId.setText(kategori.getIdKategori());
        tfNama.setText(kategori.getNamaKategori());
        taDeskripsi.setText(kategori.getDeskripsiKategori());
        
        status = "EDIT";
        lblTitle.setText("Edit Kategori");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        lblTitle3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDeskripsi = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kategori");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 70, 90), 1, true));

        lblTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(23, 70, 90));
        lblTitle.setText("Tambah Kategori");

        lblTitle1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle1.setText("ID : ");

        tfNama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle2.setText("Nama : ");

        tfId.setEditable(false);
        tfId.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle3.setText("Deskripsi : ");

        taDeskripsi.setColumns(20);
        taDeskripsi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        taDeskripsi.setLineWrap(true);
        taDeskripsi.setRows(5);
        taDeskripsi.setWrapStyleWord(true);
        taDeskripsi.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        jScrollPane1.setViewportView(taDeskripsi);

        btnSimpan.setBackground(new java.awt.Color(23, 70, 90));
        btnSimpan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(250, 255, 255));
        btnBatal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBatal))
                    .addComponent(lblTitle3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle2)
                        .addGap(31, 31, 31)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addGap(56, 56, 56)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTitle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
   
        // validasi
        if(tfNama.getText().equals("") || taDeskripsi.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Lengkapi data kategori", "Kategori", JOptionPane.WARNING_MESSAGE);
        }else{
        
               // inisialisasi tabel dan objek kategori
                KategoriTable kategoriTable = new KategoriTable();
                Kategori kategori = new Kategori();

                // isi objek kategori
                kategori.setIdKategori(tfId.getText());
                kategori.setNamaKategori(tfNama.getText());
                kategori.setDeskripsiKategori(taDeskripsi.getText());
            
            // INSERT
            if(status.equals("TAMBAH")){
                boolean insert = kategoriTable.tambahKategori(kategori); // melakukan penambahan ke tabel kategori

                if(insert == true){ // jika berhasil
                    JOptionPane.showMessageDialog(rootPane, "Kategori berhasil ditambahkan", "Kategori", JOptionPane.INFORMATION_MESSAGE);
                    
                    // mengaktifkan adminframe dan refresh halaman kategori
                    adminFrame.setEnabled(true);
                    adminFrame.pilihHalaman("kategori");
                    dispose();
                    
               }else{ // jika gagal
                    JOptionPane.showMessageDialog(rootPane, "Kategori gagal ditambah", "Kategori", JOptionPane.ERROR_MESSAGE);
                }
                
            // UPDATE
            }else{
                boolean update = kategoriTable.editKategori(kategori); // melakukan pengeditan

                if(update == true){ // jika berhasil
                    JOptionPane.showMessageDialog(rootPane, "Kategori berhasil diubah", "Kategori", JOptionPane.INFORMATION_MESSAGE);
                    
                    // mengaktifkan adminframe dan refresh halaman kategori
                    adminFrame.setEnabled(true);
                    adminFrame.pilihHalaman("kategori");
                    dispose();
                    
               }else{ // jika gagal 
                    JOptionPane.showMessageDialog(rootPane, "Kategori gagal diubah", "Kategori", JOptionPane.ERROR_MESSAGE);
                }

            }
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        adminFrame.setEnabled(true); // mengaktifkan kembali adminFrame
        dispose(); // menghilangkan frame form kategori
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KategoriFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KategoriFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KategoriFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KategoriFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KategoriFormFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JTextArea taDeskripsi;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
