/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import javax.swing.JOptionPane;
import model.Pelanggan;
import table.PelangganTable;

/**
 *
 * @author Ahya Ghifari
 */
public class PelangganFormFrame extends javax.swing.JFrame {
    
    // inisialisasi properti
    private AdminFrame adminFrame;
    private TransaksiFormFrame transaksiFormFrame;
    
    private String status = "TAMBAH";
    
    /**
     * Creates new form KategoriFormFrame
     * @param adminFrame
     */
    
    // KONSTRUKTOR UNTUK TAMBAH PELANGGAN DARI HALAMAN PELANGGAN
    public PelangganFormFrame(AdminFrame adminFrame) {
        initComponents();
        
        status = "TAMBAH";
        lblTitle.setText("Tambah Pelanggan");
        this.adminFrame = adminFrame;
        
        tfId.setVisible(false);
    }
    
    // KONSTRUKTOR UNTUK TAMBAH  KETIKA MEMBUAT TRANSAKSI
    public PelangganFormFrame(TransaksiFormFrame transaksiFormFrame) {
        initComponents();
        
        status = "TAMBAH";
        lblTitle.setText("Tambah Pelanggan");
        this.transaksiFormFrame = transaksiFormFrame;
        
        tfId.setVisible(false);
        
    }
    
    // KONSTRUKTOR UNTUK EDIT
    public PelangganFormFrame(Pelanggan pelanggan, AdminFrame adminFrame) {
        initComponents();

        status = "EDIT";
        lblTitle.setText("Edit Pelanggan");
     
        // set form sesuai pelanggan yang dipilih
        tfId.setText(String.valueOf(pelanggan.getIdPelanggan()));
        tfNama.setText(pelanggan.getNamaPelanggan());
        tfNoTelepon.setText(pelanggan.getNoTelepon());
        tfEmail.setText(pelanggan.getEmail());
        taAlamat.setText(pelanggan.getAlamat());
        
        this.adminFrame = adminFrame;
        
        tfId.setVisible(false);
        this.setTitle("Edit Pelanggan");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        tfNoTelepon = new javax.swing.JTextField();
        lblTitle5 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pelanggan");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 70, 90), 1, true));

        lblTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(23, 70, 90));
        lblTitle.setText("Tambah Pelanggan");

        tfNama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle2.setText("Nama : ");

        lblTitle3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle3.setText("Alamat : ");

        taAlamat.setColumns(20);
        taAlamat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        taAlamat.setLineWrap(true);
        taAlamat.setRows(5);
        taAlamat.setWrapStyleWord(true);
        taAlamat.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jScrollPane1.setViewportView(taAlamat);

        btnSimpan.setBackground(new java.awt.Color(23, 70, 90));
        btnSimpan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(250, 255, 255));
        btnBatal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        lblTitle4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle4.setText("No Telepon : ");

        tfNoTelepon.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle5.setText("Email : ");

        tfEmail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        tfId.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal))
                            .addComponent(lblTitle3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle2)
                                    .addComponent(lblTitle4)
                                    .addComponent(lblTitle5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNama, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(tfNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfEmail)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle4)
                    .addComponent(tfNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTitle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        if(adminFrame != null){
            adminFrame.setEnabled(true);
        }else{
            transaksiFormFrame.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        String nama = tfNama.getText();
        String no_telepon = tfNoTelepon.getText();
        String email = tfEmail.getText();
        String alamat = taAlamat.getText();
        
        if(nama.equals("") || no_telepon.equals("") || email.equals("") || alamat.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Semua form belum terisi", "Tambah Pelanggan", JOptionPane.ERROR_MESSAGE);
        }else if(no_telepon.length() > 15){
            JOptionPane.showMessageDialog(rootPane, "Isi no telepon dengan benar", "Tambah Pelanggan", JOptionPane.ERROR_MESSAGE);
        }else{
            Pelanggan p = new Pelanggan();
            p.setNamaPelanggan(nama);
            p.setNoTelepon(no_telepon);
            p.setEmail(email);
            p.setAlamat(alamat);
            
            PelangganTable pT = new PelangganTable();
            
            // TAMBAH PELANGGAN
            if(status.equals("TAMBAH")){
                boolean insert = pT.tambahPelanggan(p);
            
                if(insert == true){
                    JOptionPane.showMessageDialog(rootPane, "Pelanggan " + nama + " berhasil ditambahkan.", this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                
                    if(adminFrame != null){
                        
                        adminFrame.setEnabled(true);
                        adminFrame.pilihHalaman("pelanggan");
                    
                    }else{
                        
                        transaksiFormFrame.refreshPelanggan();
                        transaksiFormFrame.setVisible(true);
            
                    }
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Pelanggan gagal ditambahkan", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                }
            
            // EDIT PELANGGAN
            }else{
                p.setIdPelanggan(Integer.parseInt(tfId.getText()));
                boolean update = pT.ubahPelanggan(p);
                
                if(update == true){
                    JOptionPane.showMessageDialog(rootPane, "Pelanggan " + nama + " berhasil diubah.", this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                
                    adminFrame.pilihHalaman("pelanggan");
                
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Pelanggan gagal diubah", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                }
            }            
        }
    }//GEN-LAST:event_btnSimpanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoTelepon;
    // End of variables declaration//GEN-END:variables
}