/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.PromoDiskon;
import table.PromoDiskonTable;

/**
 *
 * @author Ahya Ghifari
 */
public class PromoDiskonFormFrame extends javax.swing.JFrame {
    
    // inisialisasi properti
    private AdminFrame adminFrame;
    private String status;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    private String levelLama = "";
    private String tanggalTersediaLama = "";
    private String tanggalBerakhirLama = "";
    
    /**
     * Creates new form KategoriFormFrame
     */
    
    public PromoDiskonFormFrame(){}
    
    // KONSTRUKTOR UNTUK TAMBAH
    public PromoDiskonFormFrame(AdminFrame adminFrame) {
        initComponents();
        this.adminFrame = adminFrame;
        
        status = "TAMBAH";
        lblTitle.setText("Tambah Promo Diskon");
    }
    
    // KONTRUKTOR UNTUK EDIT
    public PromoDiskonFormFrame(AdminFrame adminFrame, PromoDiskon promoDiskon) {
        initComponents();
        this.adminFrame = adminFrame;
        
        status = "EDIT";
        lblTitle.setText("Edit Promo Diskon");
        
        // MENGISI FORM SESUAI DATA YANG DIPILIH
        tfId.setText(String.valueOf(promoDiskon.getIdPromoDiskon()));
        tfPresentase.setText(String.valueOf(promoDiskon.getPresentaseDiskon()));
        cbLevel.setSelectedItem(promoDiskon.getLevel());
        try {
            dpTanggalTersedia.setSelectedDate(dateFormat.parse(promoDiskon.getTanggalTersedia()));
            dpTanggalBerakhir.setSelectedDate(dateFormat.parse(promoDiskon.getTanggalBerakhir()));
        } catch (ParseException ex) {
            Logger.getLogger(PromoDiskonFormFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        levelLama = promoDiskon.getLevel();
        tanggalTersediaLama = promoDiskon.getTanggalTersedia();
        tanggalBerakhirLama = promoDiskon.getTanggalBerakhir();
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpTanggalTersedia = new com.raven.datechooser.DateChooser();
        dpTanggalBerakhir = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        tfPresentase = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        lblTitle3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        cbLevel = new javax.swing.JComboBox<>();
        lblTitle4 = new javax.swing.JLabel();
        lblTitle5 = new javax.swing.JLabel();
        tfTanggalTersedia = new javax.swing.JTextField();
        tfTanggalBerakhir = new javax.swing.JTextField();

        dpTanggalTersedia.setForeground(new java.awt.Color(23, 70, 90));
        dpTanggalTersedia.setDateFormat("yyyy-MM-dd");
        dpTanggalTersedia.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dpTanggalTersedia.setTextRefernce(tfTanggalTersedia);

        dpTanggalBerakhir.setForeground(new java.awt.Color(23, 70, 90));
        dpTanggalBerakhir.setDateFormat("yyyy-MM-dd");
        dpTanggalBerakhir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dpTanggalBerakhir.setTextRefernce(tfTanggalBerakhir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Promo Diskon");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 70, 90), 1, true));

        lblTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(23, 70, 90));
        lblTitle.setText("Tambah Promo Diskon");

        lblTitle1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle1.setText("ID : ");

        tfPresentase.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle2.setText("Presentase Diskon : ");

        tfId.setEditable(false);
        tfId.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        lblTitle3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle3.setText("Level : ");

        btnSimpan.setBackground(new java.awt.Color(23, 70, 90));
        btnSimpan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(250, 255, 255));
        btnBatal.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });

        cbLevel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Level", "Classic", "Silver", "Gold", "Platinum", "Semua" }));

        lblTitle4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle4.setText("Tanggal Tersedia : ");

        lblTitle5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(28, 28, 39));
        lblTitle5.setText("Tanggal Berakhir :  ");

        tfTanggalTersedia.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        tfTanggalBerakhir.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitle4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTanggalTersedia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle2)
                                    .addComponent(lblTitle1)
                                    .addComponent(lblTitle3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(tfPresentase, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal)))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTanggalBerakhir)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle2)
                    .addComponent(tfPresentase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle3)
                    .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle4)
                    .addComponent(tfTanggalTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle5)
                    .addComponent(tfTanggalBerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        adminFrame.setEnabled(true); // mengaktifkan lagi frame admin
        dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        
        // inisialisasi tabel dan objek lalu mengisinya
        PromoDiskonTable pdTable = new PromoDiskonTable();
        PromoDiskon promoDiskon = new PromoDiskon();
        
        promoDiskon.setPresentaseDiskon(Integer.parseInt(tfPresentase.getText()));
        promoDiskon.setLevel(cbLevel.getSelectedItem().toString());
        promoDiskon.setTanggalTersedia(tfTanggalTersedia.getText());
        promoDiskon.setTanggalBerakhir(tfTanggalBerakhir.getText());
        
        // TAMBAH        
        if(status.equals("TAMBAH")){
            String insert = pdTable.tambahPromoDiskon(promoDiskon); // penambahan promo diskon

            if(insert.equals("SUCCESS")){ // jika tambah berhasil

                // mengaktifkan dan merefresh halaman promo diskon
                adminFrame.setEnabled(true); 
                adminFrame.pilihHalaman("promo-diskon");
                JOptionPane.showMessageDialog(rootPane, "Promo Diskon berhasil ditambahkan", "Promo Diskon", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                
            }else{ // jika gagal
                if(insert.contains("Promo")){
                    JOptionPane.showMessageDialog(rootPane, insert, "Promo Diskon", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Promo Diskon gagal ditambahkan", "Promo Diskon", JOptionPane.ERROR_MESSAGE);
                }
            }
        
        // EDIT
        }else{
            
            int id = Integer.parseInt(tfId.getText());
            // proses edit
            String update = pdTable.editPromoDiskon(promoDiskon, id, levelLama, tanggalTersediaLama, tanggalBerakhirLama);
            
            if(update.equals("SUCCESS")){ // jika edit berhasil

                JOptionPane.showMessageDialog(rootPane, "Promo Diskon berhasil diubah", "Promo Diskon", JOptionPane.INFORMATION_MESSAGE);
                
                // aktifkan dan refresh halaman promo diskon
                adminFrame.setEnabled(true);
                adminFrame.pilihHalaman("promo-diskon");
                dispose();
                
            }else{ // jika gagal
                if(update.contains("Promo")){
                    JOptionPane.showMessageDialog(rootPane, update, "Promo Diskon", JOptionPane.ERROR_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Promo Diskon gagal diubah", "Promo Diskon", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
        
    }//GEN-LAST:event_btnSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoDiskonFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoDiskonFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoDiskonFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoDiskonFormFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoDiskonFormFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbLevel;
    private com.raven.datechooser.DateChooser dpTanggalBerakhir;
    private com.raven.datechooser.DateChooser dpTanggalTersedia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfPresentase;
    private javax.swing.JTextField tfTanggalBerakhir;
    private javax.swing.JTextField tfTanggalTersedia;
    // End of variables declaration//GEN-END:variables
}
